apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getting-started
  template:
    metadata:
      labels:
        app: getting-started
    spec:
      containers:
        - name: getting-started
          image: ghcr.io/oak06/kubernetes-getting-started:0.2
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: DB_HOST
              value: postgres-service.getting-started.svc.cluster.local
            - name: DB_NAME
              value: getting_started
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
      imagePullSecrets:
        - name: github
