apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: getting-started-stateful
spec:
  selector:
    matchLabels:
      app: getting-started-stateful
  serviceName: getting-started-stateful
  replicas: 2
  template:
    metadata:
      labels:
        app: getting-started-stateful
    spec:
      containers:
        - name: getting-started-stateful
          image: ghcr.io/oak06/kubernetes-getting-started:0.2
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: DB_HOST
              value: postgres-service.default.svc.cluster.local
            - name: DB_NAME
              value: getting_started
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
      imagePullSecrets:
        - name: github
