apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: getting-started-stateful
spec:
  selector:
    matchLabels:
      app: getting-started-stateful
  serviceName: getting-started-stateful
  replicas: 2
  template:
    metadata:
      labels:
        app: getting-started-stateful
    spec:
      containers:
        - name: getting-started-stateful
          image: ghcr.io/oak06/getting-started:0.1
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: db_name
              value: getting-started-db
            - name: db_user
              value: admin
            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: getting-started-db
                  key: password
      imagePullSecrets:
        - name: github
